#!/bin/bash
# 디버깅 함수 사용 안내

echo "=========================================="
echo "도시 표시 문제 디버깅 함수"
echo "=========================================="
echo ""
echo "이 파일은 콘솔에서 실행할 디버깅 명령어를 제공합니다."
echo ""
echo "1. 브라우저에서 고려만리지도 사이트 열기"
echo "2. F12를 눌러 개발자 도구 열기"
echo "3. 콘솔(Console) 탭으로 이동"
echo "4. 아래 명령어 복사하여 실행"
echo ""
echo "=========================================="
echo "명령어 예시"
echo "=========================================="
echo ""
echo "⭐ [신규] 완전히 표시가 누락되는 성 찾기:"
echo "    findCompletelyHiddenCastles()"
echo ""
echo "⭐ [신규] 모든 성의 상태를 종합적으로 검사:"
echo "    auditAllCastles()"
echo ""
echo "[1] 2000년 1월 기준 표시되지 않는 도시 찾기:"
echo "    findHiddenCastles()"
echo ""
echo "[2] 1200년 6월 기준 표시되지 않는 도시 찾기:"
echo "    findHiddenCastles(1200, 6)"
echo ""
echo "[3] 918년 1월 기준 표시되지 않는 도시 찾기:"
echo "    findHiddenCastles(918, 1)"
echo ""
echo "[4] '서울' 도시의 상세 정보 확인:"
echo "    analyzeCastle('서울')"
echo ""
echo "[5] '평양' 도시의 상세 정보 확인:"
echo "    analyzeCastle('평양')"
echo ""
echo "[6] 결과를 변수에 저장하여 분석:"
echo "    const hidden = findCompletelyHiddenCastles()"
echo "    hidden.forEach(c => console.log(c.name, c.reason))"
echo ""
echo "=========================================="
echo "기대 결과"
echo "=========================================="
echo ""
echo "✓ findCompletelyHiddenCastles() 실행 시:"
echo "  - 어떤 시점에서도 표시되지 않는 성의 목록이 출력됨"
echo "  - 각 성별 누락 사유가 명시됨"
echo ""
echo "✓ auditAllCastles() 실행 시:"
echo "  - 성 데이터의 종합 검사 결과가 출력됨"
echo "  - 정상/문제가 있는 성이 분류됨"
echo ""
echo "✓ findHiddenCastles() 실행 시:"
echo "  - 표시되지 않는 도시의 목록이 콘솔에 테이블로 출력됨"
echo "  - 각 도시별 문제점이 명시됨"
echo ""
echo "✓ analyzeCastle('도시명') 실행 시:"
echo "  - 도시의 모든 히스토리와 시간 범위가 출력됨"
echo "  - 각 히스토리의 국가 ID가 표시됨"
echo ""
echo "=========================================="
